### ISSUE TITLE
Add my tracker please ?

### ISSUE THREAD

**Issue by nikosuk** [ryelogheat/xpbot#14]
Hello, thank you for this lovely piece of software !!

could you please consider adding my tracker to the list of supported trackers ?
i could provide information / invite
Thanks in advance

**Comment by ryelogheat** [comment]
Create the site template first (you can get more info on how it works here https://github.com/ryelogheat/xpbot/wiki/Tracker-Templates) then let me know so I can verify it works & add it to the list of supported sites :+1:

**Comment by nikosuk** [comment]
i have created the site template , ( still in testing ) 
i managed to make it work ... but when trying to upload torrent, it gives me : 

Do you want to upload with these settings? [y/n]: y
HTTP response status code: 404
Upload failed

What am i doing wrong?
Thanks for your help

**Comment by ryelogheat** [comment]
tbh not quite sure rn, I've been troubleshooting the same issue on telly with another user. It seems that using python3.9 solved the issue but again I'm not quite sure why, still looking into it

**Comment by ryelogheat** [comment]
btw could you send me an invite? Or create a temporarily account for me so I can test the script? My email is ryelogheat@belko.pw

**Comment by ryelogheat** [comment]
telly.wtf has been added 


I also recommend pulling the most recent version of the script & running again, turns out UNIT3D sites will return what keys you are missing when uploading (common issue with the 404 errors) the script will print that info out right after you confirm you want to upload (auto_mode disabled)

You can add the missing keys to that trackers *.json template file, the script will automatically assign that key a 0 if we don't have any corresponding data for it (e.g. required TVDB ID for some movie)

**Comment by nikosuk** [comment]
It works now,
i am not sure if you fixed something, but i installed Python3.9 in any case
Thank you for your kind help

and once again thank you for this project
