### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode character '\u2764' in position 30: character maps to <undefined>

### ISSUE THREAD

**Issue by Ruke805** [ryelogheat/xpbot#27]
Hi, I'm getting this error. Could someone help me?
![image](https://user-images.githubusercontent.com/62116034/125658943-3577de9d-d101-47f7-9de0-e841b09c2998.png)

Thanks

**Comment by ryelogheat** [comment]
It has to do with the emoji/message that gets added to the bottom of the description

The easiest way to fix it would be to just get rid of the emoji, to do that you need to open `auto_upload.py` and make your way to line number `1921`

That line (**1921**) should look like this: 
`description.write(f'{bbcode_line_break}{bbcode_line_break} Uploaded with [color=red]{"<3" if str(tracker).upper() == "BHD" else "❤"}[/color] using [url=https://github.com/ryelogheat/xpbot]XpBot[/url][/center]')`

Delete the whole thing and instead paste this line:
`description.write(f'{bbcode_line_break}{bbcode_line_break} Uploaded with [color=red]<3[/color] using [url=https://github.com/ryelogheat/xpbot]XpBot[/url][/center]')`


Make sure you put the new line in the same spot as the old one (use spaces) otherwise you might get a *inconsistent use of tabs and spaces* error & the script won't run

**Comment by Ruke805** [comment]
Nice! Worked well, thanks!
