### ISSUE TITLE
nfo_file not uploading.

### ISSUE THREAD

**Issue by ghost** [ryelogheat/xpbot#36]
Hi I get my tracker working all fine, but .nfo is not uploaded.
Neither by autodetect or if I give the path to .nfo file.

**Comment by ryelogheat** [comment]
I disabled the inclusion of a nfo file/text in the final upload POST request because it kept failing on BHD & BLU. I don't know if that's since been fixed or if it was ever broken on other sites.

But if you want to try & enable nfo uploads, you can try uncommenting the following lines in **auto_upload.py** `1423`, `1425` (I think line `1424` was an unfinished comment so you can probably just delete that line) 

https://github.com/ryelogheat/xpbot/blob/master/auto_upload.py#L1422 (this is where the commented out code starts)

**Comment by ghost** [comment]
Didn't make it work on mine tracker, so it may be UNIT3D now, because it used to work.
I'll try a pristine tracker.

**Comment by ghost** [comment]
It did not work on a pristine tracker.

**Comment by ghost** [comment]
Need to put this under requirement in site json-file

    "nfo": "file",
