### ISSUE TITLE
rtorrent.rc

### ISSUE THREAD

**Issue by FuNFooKaS** [ryelogheat/xpbot#44]
when i add these lines in my .rtorrent.rc file it will not start after i restart rtorrent.

method.insert = d.data_path, simple, "if=(d.is_multi_file), (cat,(d.directory),/), (cat,(d.directory),/,(d.name))"
/home/fookas/xpbot-master/rtorrent_on_complete_reupload.sh
method.set_key = event.download.finished,complete,"execute=/home/fookas/xpbot-master/rtorrent_on_complete_reupload.sh,$d.name=,$d.data_path=,$d.custom1=,$d.custom=upload_to_tracker"

**Comment by FuNFooKaS** [comment]
Development of  this dead?

**Comment by ryelogheat** [comment]
Check out https://gitlab.com/NoobMaster669/gg-bot-uploader for a more active fork/project. I'm only maintaining & fixing critical issues for this project now

**Comment by ganjaparadise** [comment]
This fork appear dead for me ! Right ?

**Comment by ryelogheat** [comment]
I don't think it's dead, he probably just has no reason to update it since everything seemingly works. 

He might just be maintaining his fork (That's what I do for this project). Just maintain, keep it running but not add any major new features

**Comment by ganjaparadise** [comment]
I see nothing more than the config.env and the readme.txt on this gitlab, maybe I’m drunk ! Anyway if someone have this gitlab feel free to contact me, I think I come read every issue on your project to late xD

**Comment by ryelogheat** [comment]
He packages it as a docker container, you need to install Docker then pull the image from https://hub.docker.com/r/noobmaster669/gg-bot-uploader

He has instructions here on how to do all this at https://gitlab.com/NoobMaster669/gg-bot-uploader#basic-setup-docker

**Comment by ganjaparadise** [comment]
Oh ok, don’t pay attention maybe I’m drunk :-)
But what I know from docker you can’t have the torrent client outside the docker right ?
Or I install docker extract files and made it in bare metal os ?

**Comment by ryelogheat** [comment]
>  But what I know from docker you can’t have the torrent client outside the docker right ?

Not really relevant though since the only way you interact with a torrent client is watch directories, if you can access the watch directory from within the container then there shouldn't be any issues

Try installing Docker & getting gg-bot working, if you can do that then you can start worrying about getting it to work with your torrent client & so on. You might need to edit the code/container & create a bind mount to expose your torrent clients watch directory to the container so gg-bot could move the generated .torrent file into it 

Though before any of that, just get gg-bot working and able to upload stuff, if you can get that far then you can start looking into the torrent client stuff

**Comment by ganjaparadise** [comment]
Yeah I will for sure, but I work with your script who work differently it’s why I ask, I will give a try, I’m a really noob in docker in fact, thanks man
