### ISSUE TITLE
Regarding addition of (e.g. bluray, webdl, dvd, etc)

### ISSUE THREAD

**Issue by wololo-wololo** [ryelogheat/xpbot#51]
Hey,

so afaik the software requires you to put either of these above in, howeever, wouldnt it be possible to have sdtv or pdtv included as well?

**Comment by ryelogheat** [comment]
As long as your filename follows standard naming conventions (e.g. `Show.Title.S01E01.1080p.SRC.WEB-DL.DDP2.0.H.264-GROUP`) then the script will automatically identify it as a `webdl`. If your filename is `SomeMovie.2022.mkv` then it becomes much much harder to reliably identify the source if not totally impossible.

So as long as your filenames contains the words `sdtv` or `pdtv` then yeah I could probably work that in 

If I correctly described what it is you want then lemme know & I can work it in

**Comment by wololo-wololo** [comment]
Sorry for the late response; 
yeah, it's exactly what I was asking for. We sometimes deal with these terms especially when uploading older media.

An example would be
formula1.2002.round01.australia.pdtv.576p.x264.english

**Comment by ryelogheat** [comment]
https://github.com/ryelogheat/xpbot/commit/be47b7a4834d083c76b7d59ea17befbd8259ba32  
OK so I've added some early support for PDTV/SDTV sources & started work on supporting R4E motorsport categories (e.g. Formula 1, WRC, MotoGP, etc)

I'm think of just prompting the user for the motorsport category, this won't allow for totally automated uploads but will make my job quite simpler lol, idk what do you think? Like the script would pause midway and ask the user if this is `F1`, `F2`, `MotoGP`, etc

I could probably identify some of the easier stuff automatically (pretty much all F1 stuff I've seen starts with `Formula1` so that could be automatically selected but I'm not familiar with the naming schemes of the other motorsport types. 

(btw you mentioned you put all the categories & their IDs into your **Racing4Everyone.json** file, could you post that bit here? It'd save me the effort of having to do it myself)

**Comment by ryelogheat** [comment]
![2022-03-01_20-04](https://user-images.githubusercontent.com/80369373/156274974-2c46293f-b523-4358-8bcf-58ad4b1b725e.png)
So. many. categories. :weary:

**Comment by ryelogheat** [comment]
OK you should be all set now, I added a new arg `-justfile` which automatically sets the tmdb & imdb to 0 so you don't have to manually do it anymore & it uses the filename (periods replaced with spaces) for the torrent title. 

I also finished adding all R4E categories and you should now be prompted when uploading to R4E to choose one (see screenshot above). 

So for R4E which doesn't have much content that has a TMDB/IMDB ID I suggest you use the `-justfile` arg
`python auto_upload.py -t r4e -p  formula1.2002.round01.australia.pdtv.576p.x264.english.mkv -justfile`

Test it out & lemme know how it goes (or if it even works lol)

**Comment by wololo-wololo** [comment]
Thanks a lot for your work! 

I tested it and it worked very well! Thank you!
