### ISSUE TITLE
Adding categories

### ISSUE THREAD

**Issue by wololo-wololo** [ryelogheat/xpbot#53]
Hey, me again and I am terribly sorry for probably opening up some issues now with hopefully not too time consuming requests, however, I tried to use the tool again (the original one) and it worked, but it will only upload into "Motorsport Movies". On our very old version of the upload tool we were able to select the available categories (which are quite a few) and to upload right into it.

I also pushed a commit (is that the right wording?) for the site template, adding our categories + IDs, but using this changed site template gives out a 404 error when uploading files, so I probably screwed something up. 

How can we implement all the categories into the script?

**Comment by ryelogheat** [comment]
The last time I saw this issue the problem was an outdated `<tracker>.json` file, specifically the script is trying to pass outdated/extra keys in the final POST upload request. 

For your tracker I had to update `auto_upload.py` **and** `racing4everyone.json` so just updating one or the other isn't good enough. You have to`git pull` the entire repo (update the whole thing)

**Comment by wololo-wololo** [comment]
Hey, thanks for your quick response. 

It sounds like you're responding to my original issue, which I edited a few times as the issue occured actually after I, myself, have edited the .json file, because I wanted it to include all possible categories - obviously didn't do it right.

What exactly do I need to change in order for it to contain all our possible categories? (33!)

**Comment by ryelogheat** [comment]
Hey, lets move this issue to https://github.com/ryelogheat/xpbot/issues/51 I'm working on both problems (categories & source types at the same time) so we can just keep it contained to https://github.com/ryelogheat/xpbot/issues/51
